### ISSUE TITLE
Change Controls

### ISSUE THREAD

**Issue by Zynh0722** [NerdHerd4043/2020_InfiniteRecharge#1]
Current Scheme:
X: Feeder && Flywheel
A: if(X) { Kickup }

Ideal Scheme: 
X: Feeder && Kickup
A: Flywheel

Sub-Optimal Scheme:
X: Feeder
A: Flywheel
Y: Kickup

**Comment by nullcubee** [comment]
Current Scheme:
A: Feeder
Y: Flywheel
X: Kickup
